read_scores: "config/read_scores.txt"
assembly: "../smrtrenseq_assembly/assembly/Gemson/Gemson.contigs.fasta"
assembly_title: "Gemson"
reference: "config/PGSC_DM_v4.03_pseudomolecules.fasta"
assoc_threshold: 26
references: "config/references.txt"
blast_genome: "config/PGSC_DM_v4.03_pseudomolecules.fasta"
