import pandas as pd
from snakemake.utils import validate

configfile: "config/config.yaml"

read_scores = pd.read_table(config["read_scores"], header=0).set_index(["sample"], drop=False)
validate(read_scores, "read_scores_schema.yaml")

references = pd.read_table(config["references"], header=0).set_index(["reference"], drop=False)
validate(references, "references_schema.yaml")

def get_reads(wildcards):
    return [read_scores["R1"][wildcards.sample], read_scores["R2"][wildcards.sample]]

def get_reference(wildcards):
    return references["assembly"][wildcards.reference]

include: "rules/jellyfish.smk"
include: "rules/accessions.smk"
include: "rules/matrix.smk"
include: "rules/phenotype.smk"
include: "rules/nlr_annotator.smk"
include: "rules/run_association.smk"
include: "rules/plotting.smk"
include: "rules/fastp.smk"
include: "rules/blast.smk"

rule all:
    input:
        expand("results/{reference}_filtered_contigs.txt", reference=references["reference"]),
        expand("images/{reference}_blast_plot.png", reference=references["reference"])
