Reference_Fasta: "config/HR02_Gemson_candidates.fa"


CDS_Bed: "config/HR02_Gemson_candidates.bed"


scoreMinRelaxed: "L,0,-0.24"


samples: "config/samples.tsv"


adaptor_path_1: "config/Index2varN.fasta"


adaptor_path_2: "config/Universal_var.fasta"


gene_groups: "drenseq_groups.txt"


ploidy: "4"


ulimit: "1024"
