Reference_Fasta: "/path/to/reference/fasta"


CDS_Bed: "/path/to/CDS/bed/file"


scoreMinRelaxed: "L,0,-0.24"


samples: "/path/to/sample/sheet"


adaptor_path_1: "/path/to/adaptors/Index2varN"


adaptor_path_2: "/path/to/adaptors/Universal_var"


baits_sequences: "/path/to/adaptors/baits_sequences"


BLAST_identity: "percentage_identity_threshold_for_baits_blast"
 
 
BLAST_coverage: "coverage_threshold_for_baits_blast"


Flanking_region: "flanking_region_for_extracting_bait_related_sequences"


ulimit: "max_number_of_open_files_allowed"


maximum_alignments: "maximal_alignments_per_read_for_bowtie2"
